### ISSUE TITLE
Invalid parameter format for ACH tokenize

### ISSUE THREAD

**Issue by mhelke** [weareseeed/react-square-web-payments-sdk#110]
### Describe the bug

This package has worked well with my Square sandbox account. After I switched to the production environment, I am unable to make ACH payments.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-bsyrq3?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

1. Click the ACH payment button.
2. Notice the error in the console.

### Expected behavior

I expect the ACH payment button to open the payment modal when clicked. Instead what I'm seeing is the following error:
```
square.js:3  InvalidOptionError: option: 'Invalid parameter format for ACH tokenize'
    at square.js:3:222416
    at Generator.next (<anonymous>)
    at Lc (square.js:3:220506)
    at s (square.js:3:220710)
    at square.js:3:220771
    at new Promise (<anonymous>)
    at square.js:3:220650
    at kc.tokenize (square.js:3:224254)
    at Object.handlePayment (ach.tsx:64:1)
    at HTMLButtonElement.<anonymous> (use-event-listener.ts:31:1)
    at HTMLButtonElement.n (square.js:3:99306)
(anonymous) @ square.js:3
overrideMethod @ console.js:288
handlePayment @ ach.tsx:82
await in handlePayment
(anonymous) @ use-event-listener.ts:31
n @ square.js:3
```

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/47f9ebba-9c31-4fd2-82ac-c9e6919a15bd)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 3.2.1

### Additional context

The same code works fine when I replace the application ID and the locationId with the sandbox values.

**Comment by djfdev** [comment]
We are seeing this same error in both our production and development environments, any updates?

**Comment by dakotawalker** [comment]
It looks like the issue is happening in the tokenize method on ach.tsx:64 `const result = await ach.tokenize({accountHolderName,});`

```typescript
 try {
      const result = await ach.tokenize({
        accountHolderName,
      });

      if (result.status === 'OK') {
        const tokenizedResult = await cardTokenizeResponseReceived(result);
        return tokenizedResult;
      }

      let message = `Tokenization failed with status: ${result.status}`;
      if (result?.errors) {
        message += ` and errors: ${JSON.stringify(result?.errors)}`;

        throw new Error(message);
      }

      console.warn(message);
    } catch (error) {
      console.error(error);
    } finally {
      setIsSubmitting(false);
    }
```

**Comment by abbyhowell** [comment]
From the [square docs](https://developer.squareup.com/docs/web-payments/add-ach#2-get-the-payment-token-from-the-ach-payment-method):

> Square is required to capture authorization for any one-time or recurring ACH payments. This authorization must appear as part of the payment flow for an application. Buyers accept authorizations by interacting with a user interface element of the payment form, such as a “Pay” or “Submit” button. All existing applications that process one-time ACH payments must migrate to using the Web Payments SDK's ACH authorization flow by January 29, 2025.
> 
> To configure the ACH authorization flow, add two new parameters to ach.tokenize() before January 29, 2025 to continue processing ACH payments as documented in [2. Get the payment token from the ACH payment method](https://developer.squareup.com/docs/web-payments/add-ach#2-get-the-payment-token-from-the-ach-payment-method)
> Learn how to take ACH bank transfer payments in a web client with the Web Payments SDK.
> Guide
> . Failure to complete this step will result in ACH payments being blocked.
> 
> The parameters to add include:
> 
> Intent - You must specify your intention to charge the buyer.
> Total - You must specify the amount and currency for the charge.

**Comment by ntheile** [comment]
@mhelke @kaid-resonite  has anyone got this working? i tried a few of forks out there and was able to get the new ACH screen within Plaid (see below) that adds the "One time charge" intent info (i assume it will show recurring or store if you add that intent). The problem is, I never receive a callback with the token after clicking confirm.

<img width="503" alt="Image" src="https://github.com/user-attachments/assets/29eeb4ec-37dd-4aa0-ad89-11b3c6b1a5ec" />
